Add a build-status job for workflows (#1153)
- Syncs https://github.com/GradleUp/shadow/commit/da9c615867eaef9e703d220f70813ba30450d5d1.
- Refs https://jakewharton.com/fan-in-to-a-single-required-github-action.

Co-authored-by: Gabriel Ittner <gabriel.ittner@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,3 +47,19 @@ jobs:
 
       - name: Build with Gradle
         run: ./gradlew build --stacktrace -DtestJavaVersion=${{ matrix.java_version }} -DtestConfigMethod=${{ matrix.test_config_method }}
+
+  # Status check that is required in branch protection rules.
+  build-status:
+    needs:
+      - build
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+          echo "All required jobs completed successfully."
